spring:
 batch:
  job:
   enabled: false
   names:  ${job.name:NONE}
  jdbc:
   initialize-schema: always 
# batch-core script sql을 실행 
# batch-core package 안에 초기화 sql 문들이 들어있다. 
# 기본적으로 메모리 DB들은 자동적으로 실행될 때 해당 스크립트들을 실행하고 다른 종류에 데이터베이스들은 위와 같은 설정으로 script sql을 실행시킬 수 있다.

 datasource: 
  driverClassName: org.mariadb.jdbc.Driver 
  url: jdbc:mariadb://localhost:3306/bbs
  username: root
  password: 1234
 
logging:
  level:
    root: info
    
main:
  allow-bean-definition-overriding=true 

profiles:
  logging-infologging:  
  file: logs/application.log  
  level:    
  org.thymeleaf: INFO    
  org.springframework.web: INFO    
  org.hibernate.SQL: INFO    
  org.quartz.core: INFO    
  org.h2.server.web: INFO 
---
profiles:
  logging-debuglogging:  
  file: logs/application.log  level:    
  org.thymeleaf: DEBUG    
  org.springframework.web: DEBUG    
  org.hibernate.SQL: DEBUG    
  org.quartz.core: DEBUG    
  org.h2.server.web: DEBUG 
  
---
profiles:
  logging-daily
  logging:  
    config: classpath:logback-spring.xml
    
 