spring:
 batch:
  job:
   names: ${job.name:NONE}
  jdbc:
   initialize-schema: never
   
 jpa:
  hibernate:
   ddl-auto: update
   use-new-id-generator-mapping: true

 datasource: 
  driverClassName: org.mariadb.jdbc.Driver 
  url: jdbc:mariadb://localhost:3306/bbs
  username: root
  password: 1234

 
logging:
  level:
    root: info
    
main:
  allow-bean-definition-overriding=true 

profiles:
  logging-infologging:  
  file: logs/application.log  
  level:    
  org.thymeleaf: INFO    
  org.springframework.web: INFO    
  org.hibernate.SQL: INFO    
  org.quartz.core: INFO    
  org.h2.server.web: INFO 
---
profiles:
  logging-debuglogging:  
  file: logs/application.log  level:    
  org.thymeleaf: DEBUG    
  org.springframework.web: DEBUG    
  org.hibernate.SQL: DEBUG    
  org.quartz.core: DEBUG    
  org.h2.server.web: DEBUG 
  
---
profiles:
  logging-daily
  logging:  
    config: classpath:logback-spring.xml
    
 